#! /bin/sh
### BEGIN INIT INFO
# Provides:          bodhibuilder-firstboot
# Required-Start:    $remote_fs $syslog $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run firstboot items for bodhibuilder after a remastered system has been installed
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
        #REM302
        if [ "`cat /proc/cmdline | grep casper`" = "" ]; then
            [ "$VERBOSE" != no ] && log_begin_msg "Running bodhibuilder-firstboot"
            # Removes this script from boot:
            (sleep 60 && update-rc.d -f bodhibuilder-firstboot remove) &
            sed -i -e 's/root:x:/root:!:/g' /etc/shadow
            rm -rf /home/*/Desktop/ubiquity*.desktop
            ################################################
            ### Place your custom commands below this line
            # Commented out repository for Ubuntu 16.04 testing
            #~ echo " " >> /etc/apt/sources.list
            #~ echo "## Bodhi Linux Repository" >> /etc/apt/sources.list
            #~ echo "deb http://packages.bodhilinux.com/bodhi trusty main" >> /etc/apt/sources.list
            #~ echo " " >> /etc/apt/sources.list
            
            yes | cp -f /etc/default/grub.bodhi /etc/default/grub
            update-grub
            ### Place your custom commands above this line
            ################################################
            ES=$?
            [ "$VERBOSE" != no ] && log_end_msg $ES
            return $ES
        fi

        


} 

case "$1" in
    start)
        do_start
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

